name: Generating artifacts for SEI
run-name: ${{ github.actor }} is creating artifacts
on: 
    push:
        branches:
          - main
    workflow_dispatch:

jobs:
    check_env:
        runs-on: ubuntu-latest
        env:
            integration_id: 16
            sample: ${{ github.run_id }}
        steps:
            - name: Check artifacts
              run: echo 'Integration ID - ${{ env.integration_id }}'

    running-resuable-workflow:
        runs-on: ubuntu-latest
        env:
            check_run_id: 0
            modulo: 1
        steps:
            - name: Workflow Step 1
              run: echo 'Hello World';echo ${{ github.run_id }};echo ${{ env.modulo }}
            - name: Workflow Step 2 - If condition
              run: echo 'Exiting successfully'

    push_artifacts_to_sei:
        runs-on: ubuntu-latest
        steps:
            - name: Push params to SEI Endpoint
              id: push_params
              env:
                base_url: "https://testapi1.propelo.ai" # change the URL based on environment e.g. eu1, asia1, etc.
                # All workflow level environment variables can be pushed as job run params.
                # List of job run params can be supported, just need to add similar object of job run param in the below payload variable under the `params` key.
                # Note: name, value and type of param are required.
                # Param object
                #   name: Environment variable name
                #   type: Type of environment variable (default string can be passed)
                #   value: Value of environment variable
                payload: '{"integration_id":"16","repository":"${{ github.repository }}","job_run_number":"${{ github.run_number }}","job_name":"${{ github.workflow }}","params":[{"name":"docker_image","type":"string","value":"karanpanchalharness/temp-test_rep01"}, {"name":"tag","type":"string","value":"v1.1.0"}, {"name":"artifacts_created_at","type":"string","value":"2023-01-01T12:00:00.000+00:00"}]}'
              run: curl '${{ env.base_url }}/v1/cicd/push_job_run_params' -H 'accept:application/json' -H 'authorization:Apikey ${{ secrets.SEI_API_KEY }}' -H 'content-type:application/json' --data-raw '${{ env.payload }}' --compressed --globoff
